module uart_top #(
    parameter CLOCK_FREQUENCY = 50_000_000,
    parameter BAUD_RATE       = 9600,
    parameter DATA_BITS       = 8,
    parameter PARITY          = 0,
    parameter STOP_BITS       = 1
)(
    input  logic                 clock,
    input  logic                 reset_n,
    
    // UART Physical Interface
    input  logic                 rx_in,
    output logic                 tx_out,
    
    // User TX Interface
    input  logic [DATA_BITS-1:0] tx_data,
    input  logic                 tx_start,
    output logic                 tx_busy,
    output logic                 tx_done,
    
    // User RX Interface
    output logic [DATA_BITS-1:0] rx_data,
    output logic                 rx_done,
    output logic                 frame_error,
    output logic                 parity_error
);

// Internal tick signals generated by baud rate generator
logic tick_1x;
logic tick_16x;


// Baud Rate Generator
baud_rate #(
    .CLOCK_FREQUENCY(CLOCK_FREQUENCY),
    .BAUD_RATE(BAUD_RATE)
) baud_rate_inst (
    .clock(clock),
    .reset_n(reset_n),
    .tick_1x(tick_1x),
    .tick_16x(tick_16x)
);


// UART Transmitter
uart_tx #(
    .DATA_BITS(DATA_BITS),
    .PARITY(PARITY),
    .STOP_BITS(STOP_BITS)
) uart_tx_inst (
    .clock(clock),
    .reset_n(reset_n),
    .tick_1x(tick_1x),
    .tx_data(tx_data),
    .tx_start(tx_start),
    .tx_out(tx_out),
    .tx_busy(tx_busy),
    .tx_done(tx_done)
);


// UART Receiver
uart_rx #(
    .DATA_BITS(DATA_BITS),
    .PARITY(PARITY),
    .STOP_BITS(STOP_BITS)
) uart_rx_inst (
    .clock(clock),
    .reset_n(reset_n),
    .tick_16x(tick_16x),
    .rx_in(rx_in),
    .rx_data(rx_data),
    .rx_done(rx_done),
    .frame_error(frame_error),
    .parity_error(parity_error)
);

endmodule
